### ISSUE TITLE
[ASK]

### ISSUE THREAD

**Issue by jugosx** [web64/nlpserver#8]
Sorry, I just ask what algorithm is used? or method to classification text?

**Comment by web64** [comment]
Hi! 
The nlpserver doesn't do classification yet, as this would require training custom models.
Currently nlpserver provides API access to common nlp packages such as SpaCy, langid and polyglot, where their language models are used for nlp tasks.

Have a look at this list for what packages are used for the various endpoints: https://github.com/web64/nlpserver#api-endpoints
You can read the documentation for the respective package to find out how they have trained their models.

If you want to do text classification you can have a look at Facebook's fastText: https://fasttext.cc/
You can train your own models simply by generating a text file with labelled training data and running a command in the terminal.
If you want API access to the fastText model you can have a look at https://github.com/web64/laravel-fasttext

I hope this helps!

**Comment by jugosx** [comment]
Very helpfully, thankyou!

**Comment by jugosx** [comment]
Sorry, I will to ask again.  what training model is use on nlpserver?
